### ISSUE TITLE
Questions of 'similarity_matrix' in the code(i.e., the adjacency matrix)

### ISSUE THREAD

**Issue by Hongbin98** [ecrireme/SPR#1]
This is a good job. However, I wonder if there is a mistake in the calculation of similarity_matrix in Line 136, SPR.py? Since the cosine similarity of the feature itself is equal to 1, it seems to be different from the definition of adjacency matrix (i.e., 0).

**Comment by ecrireme** [comment]
Hi, thank you for your interest in our work. 
The diagonal of an adjacency matrix doesn't have to be always 0. 
A graph with self-loops has an adjacency matrix whose diagonal elements are filled with ones.
Since we consider edges in the graph as similarity, it is natural to set 1 as diagonal elements, which means that the similarity between any node itself is perfect.

**Comment by Hongbin98** [comment]
Thanks for your reply~
